/*
 * Probe every stream in the catalog and drop the ones that are definitively
 * dead, then rewrite data/stations.json and data/stations.js.
 *
 * Run:  node tools/prune-dead.mjs
 *
 * Deliberately conservative. A station is only removed for a hard failure --
 * DNS/connection failure, 404/410, 5xx, a timeout, or an HTML error page served
 * where audio should be. Anything else is kept, because plenty of hosts answer
 * a bare script probe differently than they answer a real <audio> element:
 * Zeno.fm returns 401 to an unfamiliar client, and StreamTheWorld labels a
 * perfectly good AAC stream "application/flv". Those play fine in a browser.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const catalog = JSON.parse(readFileSync(join(ROOT, 'data', 'stations.json'), 'utf8'));

async function probe(url) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 10000);
  try {
    const res = await fetch(url, {
      signal: ctrl.signal,
      redirect: 'follow',
      headers: { 'User-Agent': 'Mozilla/5.0', Icy: 'MetaData:0', Range: 'bytes=0-2048' },
    });
    const type = (res.headers.get('content-type') || '').toLowerCase();
    if (res.status === 404 || res.status === 410) return { dead: true, why: 'HTTP ' + res.status };
    if (res.status >= 500) return { dead: true, why: 'HTTP ' + res.status };
    if (/text\/html/.test(type)) return { dead: true, why: 'html page' };
    if (res.body) {
      const reader = res.body.getReader();
      const first = await Promise.race([
        reader.read(),
        new Promise((r) => setTimeout(() => r({ value: null, timedOut: true }), 8000)),
      ]);
      reader.cancel().catch(() => {});
      if (first.timedOut) return { dead: true, why: 'no bytes in 8s' };
    }
    return { dead: false, why: 'HTTP ' + res.status + ' ' + type };
  } catch (e) {
    const msg = e.name === 'AbortError' ? 'timeout' : (e.cause && e.cause.code) || e.message;
    return { dead: true, why: String(msg).slice(0, 40) };
  } finally {
    clearTimeout(timer);
  }
}

const stations = catalog.stations;
const dead = [];
let cursor = 0;
let done = 0;

await Promise.all(
  Array.from({ length: 24 }, async () => {
    while (cursor < stations.length) {
      const s = stations[cursor++];
      const r = await probe(s.url);
      if (r.dead) dead.push({ name: s.name, url: s.url, why: r.why });
      if (++done % 100 === 0) process.stdout.write(done + '/' + stations.length + ' (' + dead.length + ' dead)\n');
    }
  })
);

const deadUrls = new Set(dead.map((d) => d.url));
const kept = stations.filter((s) => !deadUrls.has(s.url));

const tallyRegion = kept.reduce((m, s) => ((m[s.region] = (m[s.region] || 0) + 1), m), {});
const tallyGenre = kept.reduce((m, s) => ((m[s.genre] = (m[s.genre] || 0) + 1), m), {});

const out = {
  ...catalog,
  count: kept.length,
  verified: new Date().toISOString().slice(0, 10),
  genres: Object.keys(tallyGenre).sort(),
  regions: catalog.regions.filter((r) => tallyRegion[r]),
  stations: kept,
};

writeFileSync(join(ROOT, 'data', 'stations.json'), JSON.stringify(out));
writeFileSync(
  join(ROOT, 'data', 'stations.js'),
  '/* Generated by tools/build-catalog.mjs, verified by tools/prune-dead.mjs on ' +
    out.verified + '. Do not edit by hand. */\n' +
    'window.RADIO_CATALOG = ' + JSON.stringify(out) + ';\n'
);
writeFileSync(join(ROOT, 'tools', 'pruned.log'), dead.map((d) => d.why + '\t' + d.name + '\t' + d.url).join('\n'));

console.log('\nDropped ' + dead.length + ', kept ' + kept.length);
console.log('Reasons:', Object.entries(dead.reduce((m, d) => ((m[d.why.replace(/\d+\.\d+.*/, '')] = (m[d.why] || 0) + 1), m), {})).sort((a, b) => b[1] - a[1]).slice(0, 10));
