/*
 * Re-derive genre and region for the shipped catalog using js/taxonomy.js,
 * without touching the network or the pruning work.
 *
 * Use after changing a classification rule in js/taxonomy.js: it relabels
 * data/stations.json + data/stations.js in place, so a rule tweak costs a
 * second instead of a full rebuild-and-reprobe.
 *
 * Run:  node tools/relabel.mjs   (then: node tools/check-taxonomy.mjs)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const T = createRequire(import.meta.url)('../js/taxonomy.js');
const catalog = JSON.parse(readFileSync(join(ROOT, 'data', 'stations.json'), 'utf8'));

let renamed = 0;
let relabelled = 0;

for (const s of catalog.stations) {
  const name = T.displayName(s.name).slice(0, 70);
  if (name !== s.name) renamed++;
  s.name = name;

  const genre = T.classifyGenre(s.tags.join(','), s.name);
  const region = T.regionFor(s.cc, s.state);
  if (genre !== s.genre || region !== s.region) relabelled++;
  s.genre = genre;
  s.region = region;
}

/* Cleaning names can reveal duplicates -- "Foo 320k mp3" and "Foo 64k aac+"
 * both become "Foo". Collapse them the same way the builder does. */
const before = catalog.stations.length;
catalog.stations = T.mergeIdentities(catalog.stations);
const collapsed = before - catalog.stations.length;
catalog.stations.sort((a, b) => b.clicks - a.clicks || a.name.localeCompare(b.name));
catalog.count = catalog.stations.length;

const tally = (key) =>
  catalog.stations.reduce((m, s) => ((m[s[key]] = (m[s[key]] || 0) + 1), m), {});

const genreTally = tally('genre');
const regionTally = tally('region');

catalog.genres = Object.keys(genreTally).sort();
catalog.regions = T.REGION_ORDER.filter((r) => regionTally[r]);

writeFileSync(join(ROOT, 'data', 'stations.json'), JSON.stringify(catalog));
writeFileSync(
  join(ROOT, 'data', 'stations.js'),
  '/* Generated by tools/build-catalog.mjs, verified by tools/prune-dead.mjs' +
    (catalog.verified ? ' on ' + catalog.verified : '') + '. Do not edit by hand. */\n' +
    'window.RADIO_CATALOG = ' + JSON.stringify(catalog) + ';\n'
);

console.log('Cleaned ' + renamed + ' name(s), relabelled ' + relabelled + ', collapsed ' +
  collapsed + ' duplicate(s) -> ' + catalog.count + ' stations.');
console.log('By genre :', Object.fromEntries(Object.entries(genreTally).sort((a, b) => b[1] - a[1])));
console.log('By region:', Object.fromEntries(Object.entries(regionTally).sort((a, b) => b[1] - a[1])));
